#!/bin/bash

# Yes, this is rather bad. Hopefully it works, though.
RUBY_BIN=$(find /usr/local/rvm/rubies/ -name 'ruby-1.9.2-*')/bin
RUBY=${RUBY_BIN}/ruby
GEM=${RUBY_BIN}/gem

$GEM install redcarpet    --version '=1.13.1'
$GEM install liquid       --version '=2.2.2'
$GEM install htmlentities --version '=4.3.0'

$RUBY /home/dotcloud/code/render/render.rb

